export {
  isArrayBindingPattern,
  isArrayLiteralExpression,
  isArrowFunction,
  isBinaryExpression,
  isBlock,
  isBreakStatement,
  isCallExpression,
  isComputedPropertyName,
  isConditionalExpression,
  isContinueStatement,
  isDoStatement,
  isElementAccessExpression,
  isExpressionStatement,
  isForStatement,
  isFunctionDeclaration,
  isFunctionExpression,
  isGetAccessor,
  isIdentifier,
  isIfStatement,
  isMethodDeclaration,
  isNumericLiteral,
  isObjectLiteralExpression,
  isOmittedExpression,
  isParenthesizedExpression,
  isPostfixUnaryExpression,
  isPrefixUnaryExpression,
  isPropertyAccessExpression,
  isPropertyAssignment,
  isReturnStatement,
  isSetAccessor,
  isShorthandPropertyAssignment,
  isSpreadAssignment,
  isStringLiteral,
  isVariableDeclarationList,
  isVariableStatement,
  isWhileStatement,
  ModifierFlags,
  NodeFlags,
  SyntaxKind,
  type ArrayLiteralExpression,
  type ArrowFunction,
  type BinaryExpression,
  type BreakStatement,
  type CallExpression,
  type ConditionalExpression,
  type ContinueStatement,
  type DoStatement,
  type ElementAccessExpression,
  type ForStatement,
  type FunctionDeclaration,
  type FunctionExpression,
  type IfStatement,
  type Node,
  type ObjectLiteralExpression,
  type ParameterDeclaration,
  type PostfixUnaryExpression,
  type PrefixUnaryExpression,
  type PropertyAccessExpression,
  type ReturnStatement,
  type SourceFile,
  type Symbol,
  type Type,
  type VariableDeclaration,
  type WhileStatement,
  // } from "@typescript/native-preview/ast";
} from "typescript";
